FROM alpine:3.11

# Install dependencies
RUN apk add --update \
        # Needs certificates for HTTPS clone
        git ca-certificates \
        # Build fails with Java 11, use Java 8 instead
        openjdk8 gradle \
        # For the native part (JNI bindings)
        g++ opencl-headers opencl-icd-loader-dev \
 && rm -rf /var/cache/apk/*



COPY --from=dopencl_alpine /opt/dopencl /opt/dopencl
ENV CPLUS_INCLUDE_PATH="/opt/dopencl/include:${CPLUS_INCLUDE_PATH}"

# Copy source files in
COPY . /tmp/cloudcl

# Build
WORKDIR /tmp/cloudcl/aparapi
RUN gradle build

WORKDIR /tmp/cloudcl
RUN gradle jar
# TODO: What to do with the JARs? And how to get the tests to pass?
